services:

  catalog:
    container_name: catalog
    build: .
    image: catalog
    env_file: .env    
    ports:
      - 8000:8000
    volumes:
      - $PWD/catalog:/catalog
      - static:/var/www/static
      - media:/var/www/media
    depends_on:
      - postgres
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  postgres:
    container_name: catalog_postgres
    image: ankane/pgvector
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  caddy:
    container_name: catalog_caddy
    image: caddy:latest    
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Caddy specific urls
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
      - type: volume
        source: media
        target: /usr/share/caddy/media
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: static
        target: /usr/share/caddy/static
        read_only: true
        volume:
          nocopy: true
    restart: unless-stopped

volumes:
  pgdata:
  static:
  media: