"""Initial

Revision ID: 82377a375299
Revises: 
Create Date: 2024-05-21 21:08:51.392618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82377a375299'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=125), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=2500), nullable=True),
    sa.Column('source_type', models.SourceType(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone='TRUE'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone='TRUE'), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('usfs_national_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=125), nullable=True),
    sa.Column('metadata_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=2500), nullable=True),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone='TRUE'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone='TRUE'), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metadata_url'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usfs_national_dataset')
    op.drop_table('documents')
    # ### end Alembic commands ###
